# .github/workflows/ci.yml
name: File Transfer Automation CI

on:
  push:
    branches: [ main, cleanup-refactor ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:${PWD}/src"
        pytest tests/ -v --cov=src --cov-report=term-missing
    
    - name: Run linting
      run: |
        flake8 src/ --max-line-length=100 --exclude=__pycache__

  build-exe:
    runs-on: windows-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build executable
      run: |
        pip install -r requirements.txt
        pyinstaller --onefile --name=file-transfer-automation src/main.py
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: file-transfer-automation.exe
        path: dist/file-transfer-automation.exe